### ISSUE TITLE
关于Gowin MCU Designer证书申请的问题

### ISSUE THREAD

**Issue by ThinkCodeStudio** [muzhiyun/TangMega-138KPro-AE350#2]
你好, 我也想尝试使用一下138k的AE350硬核, 但Gowin MCU Designer软件的证书我一直不知道怎么申请. 
可以请教下Gowin MCU Designer 证书的获取方法吗?

**Comment by nickfox-taterli** [comment]
这个用的应该是RiscV_AE350_SOC_RDS_v1.0_win(AndeSight IDE),另外授权需要额外申请,目前该内核资料相对比较少,你就当这个板子没有这个内核还好一些,跑个开源核不好吗?

**Comment by muzhiyun** [comment]
@ThinkCodeStudio 
你好，我是参照[这个页面](https://www.gowinsemi.com/en/market/featured_detail/4/)的步骤6联系Gowin申请的lic。你也可以直接发邮件给Gowin，如同[briansune](https://github.com/briansune) 提到的那样。

6 Go to http://www.gowinsemi.com/support/enquires/ and fill out form. Under “Enquiry” type “Request for AndeSight RDS for GOWIN SW Tool Chain License”
